name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile,github_actions

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: NPM Audit
        run: npm audit --audit-level=high

      - name: Build Docker Image
        run: |
          docker build --no-cache -t secure-nodejs-app:v1 .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-nodejs-app:v1
          format: table
          exit-code: 1
          severity: CRITICAL
          ignore-unfixed: true

      - name: Tag Docker Image
        run: |
          docker tag secure-nodejs-app:v1 20.244.104.148:5000/nodejs-app:v1

      - name: Push Docker Image
        run: |
          docker push 20.244.104.148:5000/nodejs-app:v1